"use client";

import {
  formatDuration,
  formatCurrency,
  getEstimationCategory,
} from "@/lib/estimation-calculator";

interface EstimationReportProps {
  estimation: {
    baseEffort: number;
    totalEffort: number;
    timeline: number;
    teamSize: number;
    costPerHour?: number;
    totalBudget?: number;
    riskLevel: string;
    skillLevel: string;
    techFamiliarity: string;
    testingLevel: string;
    confidence: number;
    breakdown: {
      skillFactor: number;
      techFactor: number;
      testFactor: number;
      riskFactor: number;
      deadlineFactor: number;
    };
    assumptions: string[];
  };
  onReset: () => void;
}

function generatePDFContent(estimation: any, category: string): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Project Estimation Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 20px; }
        .metric-box { margin: 10px 0; padding: 10px; border-left: 4px solid #3498db; background: #ecf0f1; }
        .metric-label { font-weight: bold; color: #2c3e50; }
        .metric-value { font-size: 18px; color: #2980b9; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #bdc3c7; padding: 10px; text-align: left; }
        th { background: #34495e; color: white; }
        .assumption-list { margin-left: 20px; }
        .assumption-list li { margin: 5px 0; }
        .footer { margin-top: 30px; font-size: 12px; color: #7f8c8d; border-top: 1px solid #bdc3c7; padding-top: 10px; }
      </style>
    </head>
    <body>
      <h1>📊 Project Estimation Report</h1>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>

      <h2>Key Metrics</h2>
      <div class="metric-box">
        <div class="metric-label">Project Category:</div>
        <div class="metric-value">${category}</div>
      </div>
      <div class="metric-box">
        <div class="metric-label">Total Effort:</div>
        <div class="metric-value">${estimation.totalEffort} hours (${(estimation.totalEffort / 40).toFixed(1)} weeks for 1 dev)</div>
      </div>
      <div class="metric-box">
        <div class="metric-label">Estimated Timeline:</div>
        <div class="metric-value">${formatDuration(estimation.timeline)}</div>
      </div>
      <div class="metric-box">
        <div class="metric-label">Team Size:</div>
        <div class="metric-value">${estimation.teamSize} developers</div>
      </div>
      ${estimation.totalBudget ? `
      <div class="metric-box">
        <div class="metric-label">Total Budget:</div>
        <div class="metric-value">${formatCurrency(estimation.totalBudget)} @ ${formatCurrency(estimation.costPerHour)}/hour</div>
      </div>
      ` : ''}
      <div class="metric-box">
        <div class="metric-label">Estimation Confidence:</div>
        <div class="metric-value">${estimation.confidence}%</div>
      </div>

      <h2>Effort Breakdown</h2>
      <table>
        <tr>
          <th>Component</th>
          <th>Hours</th>
        </tr>
        <tr>
          <td>Base Effort</td>
          <td>${estimation.baseEffort}</td>
        </tr>
        <tr>
          <td>Skill Level Adjustment (${estimation.breakdown.skillFactor}x)</td>
          <td>${Math.round(estimation.baseEffort * (estimation.breakdown.skillFactor - 1))}</td>
        </tr>
        <tr>
          <td>Tech Stack Adjustment (${estimation.breakdown.techFactor}x)</td>
          <td>${Math.round(estimation.baseEffort * (estimation.breakdown.techFactor - 1))}</td>
        </tr>
        <tr>
          <td>Testing Level Adjustment (${estimation.breakdown.testFactor}x)</td>
          <td>${Math.round(estimation.baseEffort * (estimation.breakdown.testFactor - 1))}</td>
        </tr>
        <tr>
          <td><strong>Total Adjusted Effort</strong></td>
          <td><strong>${estimation.totalEffort}</strong></td>
        </tr>
      </table>

      <h2>Parameters Used</h2>
      <table>
        <tr>
          <th>Parameter</th>
          <th>Value</th>
        </tr>
        <tr>
          <td>Team Skill Level</td>
          <td>${estimation.skillLevel}</td>
        </tr>
        <tr>
          <td>Tech Familiarity</td>
          <td>${estimation.techFamiliarity}</td>
        </tr>
        <tr>
          <td>Testing Level</td>
          <td>${estimation.testingLevel}</td>
        </tr>
        <tr>
          <td>Risk Level</td>
          <td>${estimation.riskLevel}</td>
        </tr>
      </table>

      <h2>Key Assumptions</h2>
      <ul class="assumption-list">
        ${estimation.assumptions.map((a: string) => `<li>${a}</li>`).join('')}
      </ul>

      <div class="footer">
        <p>This report was generated by DeliveryForge - Complexity Analysis & Estimation Tool</p>
      </div>
    </body>
    </html>
  `;
}

export function EstimationReport({
  estimation,
  onReset,
}: EstimationReportProps) {
  const handleDownloadPDF = () => {
    const category = getEstimationCategory(estimation.totalEffort / 8);
    const htmlContent = generatePDFContent(estimation, category);

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `estimation-report-${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  const category = getEstimationCategory(estimation.totalEffort / 8); // Back-calculate complexity
  const effortBreakdown = {
    base: estimation.baseEffort,
    skillAdjustment: Math.round(
      estimation.baseEffort * (estimation.breakdown.skillFactor - 1)
    ),
    techAdjustment: Math.round(
      estimation.baseEffort * (estimation.breakdown.techFactor - 1)
    ),
    testAdjustment: Math.round(
      estimation.baseEffort * (estimation.breakdown.testFactor - 1)
    ),
    riskAdjustment: Math.round(
      estimation.baseEffort * (estimation.breakdown.riskFactor - 1)
    ),
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200 rounded-lg p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 mb-2">
              ✅ Estimation Generated
            </h2>
            <p className="text-gray-600">
              Project Category: <span className="font-semibold">{category}</span>
            </p>
          </div>
          <div className="text-right">
            <div className="text-5xl font-bold text-green-600 mb-1">
              {estimation.timeline}
            </div>
            <div className="text-sm text-gray-600">weeks</div>
          </div>
        </div>
      </div>

      {/* Key Metrics Grid */}
      <div className={`grid grid-cols-1 ${estimation.totalBudget ? "md:grid-cols-2 lg:grid-cols-4" : "md:grid-cols-3"} gap-4`}>
        {/* Total Effort */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="text-sm font-semibold text-blue-900 mb-1">
            Total Effort
          </div>
          <div className="text-3xl font-bold text-blue-600">
            {estimation.totalEffort}
          </div>
          <div className="text-xs text-blue-700 mt-2">
            {(estimation.totalEffort / 40).toFixed(1)} weeks (1 developer)
          </div>
        </div>

        {/* Timeline */}
        <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
          <div className="text-sm font-semibold text-purple-900 mb-1">
            Estimated Timeline
          </div>
          <div className="text-3xl font-bold text-purple-600">
            {formatDuration(estimation.timeline)}
          </div>
          <div className="text-xs text-purple-700 mt-2">
            {estimation.teamSize} developers available
          </div>
        </div>

        {/* Total Budget - Conditional */}
        {estimation.totalBudget && (
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <div className="text-sm font-semibold text-green-900 mb-1">
              Total Budget
            </div>
            <div className="text-3xl font-bold text-green-600">
              {formatCurrency(estimation.totalBudget)}
            </div>
            <div className="text-xs text-green-700 mt-2">
              @ {formatCurrency(estimation.costPerHour!)}/hour
            </div>
          </div>
        )}

        {/* Confidence */}
        <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
          <div className="text-sm font-semibold text-orange-900 mb-1">
            Estimation Confidence
          </div>
          <div className="text-3xl font-bold text-orange-600">
            {estimation.confidence}%
          </div>
          <div className="w-full bg-orange-200 rounded-full h-2 mt-2">
            <div
              className="bg-orange-600 h-2 rounded-full"
              style={{ width: `${estimation.confidence}%` }}
            ></div>
          </div>
        </div>
      </div>

      {/* Detailed Breakdown */}
      <div className="bg-white border border-gray-200 rounded-lg p-6">
        <h3 className="text-xl font-bold text-gray-900 mb-4">
          📊 Effort Breakdown
        </h3>
        <div className="space-y-3">
          <div className="flex justify-between items-center pb-3 border-b">
            <span className="text-gray-700">Base Effort</span>
            <span className="font-semibold text-gray-900">
              {estimation.baseEffort} hours
            </span>
          </div>
          <div className="flex justify-between items-center pb-3 border-b">
            <span className="text-gray-700">
              Skill Level Adjustment ({estimation.breakdown.skillFactor}x)
            </span>
            <span className="font-semibold text-gray-900">
              {effortBreakdown.skillAdjustment > 0 ? "+" : ""}
              {effortBreakdown.skillAdjustment} hours
            </span>
          </div>
          <div className="flex justify-between items-center pb-3 border-b">
            <span className="text-gray-700">
              Tech Stack Adjustment ({estimation.breakdown.techFactor}x)
            </span>
            <span className="font-semibold text-gray-900">
              {effortBreakdown.techAdjustment > 0 ? "+" : ""}
              {effortBreakdown.techAdjustment} hours
            </span>
          </div>
          <div className="flex justify-between items-center pb-3 border-b">
            <span className="text-gray-700">
              Testing Level Adjustment ({estimation.breakdown.testFactor}x)
            </span>
            <span className="font-semibold text-gray-900">
              {effortBreakdown.testAdjustment > 0 ? "+" : ""}
              {effortBreakdown.testAdjustment} hours
            </span>
          </div>
          <div className="flex justify-between items-center pt-2">
            <span className="text-lg font-bold text-gray-900">
              Total Adjusted Effort
            </span>
            <span className="text-lg font-bold text-green-600">
              {estimation.totalEffort} hours
            </span>
          </div>
        </div>
      </div>

      {/* Parameters Used */}
      <div className="bg-white border border-gray-200 rounded-lg p-6">
        <h3 className="text-xl font-bold text-gray-900 mb-4">
          ⚙️ Parameters Used
        </h3>
        <div className={`grid grid-cols-1 ${estimation.totalBudget ? "md:grid-cols-2" : ""} gap-6`}>
          <div>
            <div className="text-sm font-semibold text-gray-600 mb-2">
              Team Configuration
            </div>
            <div className="space-y-2 text-sm text-gray-700">
              <div>
                <span className="font-medium">Team Size:</span>{" "}
                {estimation.teamSize} developers
              </div>
              <div>
                <span className="font-medium">Skill Level:</span>{" "}
                {estimation.skillLevel}
              </div>
              <div>
                <span className="font-medium">Risk Level:</span>{" "}
                {estimation.riskLevel}
              </div>
            </div>
          </div>
          <div>
            <div className="text-sm font-semibold text-gray-600 mb-2">
              Project Requirements
            </div>
            <div className="space-y-2 text-sm text-gray-700">
              <div>
                <span className="font-medium">Tech Familiarity:</span>{" "}
                {estimation.techFamiliarity}
              </div>
              <div>
                <span className="font-medium">Testing Level:</span>{" "}
                {estimation.testingLevel}
              </div>
              {estimation.costPerHour && (
                <div>
                  <span className="font-medium">Cost Per Hour:</span>{" "}
                  {formatCurrency(estimation.costPerHour)}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Assumptions */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
        <h3 className="text-xl font-bold text-gray-900 mb-4">
          📝 Key Assumptions
        </h3>
        <ul className="space-y-2">
          {estimation.assumptions.map((assumption, idx) => (
            <li key={idx} className="flex gap-3 text-sm text-gray-700">
              <span className="text-blue-600 font-semibold">✓</span>
              <span>{assumption}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 pt-4">
        <button
          onClick={onReset}
          className="flex-1 px-4 py-3 border border-gray-300 rounded-lg text-gray-700 font-semibold hover:bg-gray-50 transition"
        >
          🔄 Generate New Estimation
        </button>
        <button
          onClick={handleDownloadPDF}
          className="flex-1 px-4 py-3 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700 transition"
        >
          📥 Download Report (HTML/PDF)
        </button>
      </div>
    </div>
  );
}
